project_id = "upiypxzjaagithghxayv"

[functions.send-password-reset]
verify_jwt = false

[functions.notify-demographic-submission]
verify_jwt = false

[functions.send-application-approval]
verify_jwt = false

[functions.notify-withdrawal]
verify_jwt = false

[functions.import-transactions]
verify_jwt = false

[functions.send-brand-invitation]
verify_jwt = false

[functions.notify-campaign-application]
verify_jwt = false

[functions.sync-shortimize-analytics]
verify_jwt = true

[functions.track-shortimize-account]
verify_jwt = true

[functions.check-task-reminders]
verify_jwt = false

[functions.discord-oauth]
verify_jwt = false