project_id = "upiypxzjaagithghxayv"

[functions.approve-campaign-application]
verify_jwt = true

[functions.get-campaign-users]
verify_jwt = true

[functions.get-campaign-transactions]
verify_jwt = true

[functions.get-campaign-applications]
verify_jwt = true

[functions.create-campaign-payment]
verify_jwt = true

[functions.create-payment-api]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.notify-demographic-submission]
verify_jwt = false

[functions.send-application-approval]
verify_jwt = false

[functions.notify-withdrawal]
verify_jwt = false

[functions.import-transactions]
verify_jwt = false

[functions.send-brand-invitation]
verify_jwt = false

[functions.notify-campaign-application]
verify_jwt = false

[functions.sync-shortimize-analytics]
verify_jwt = true

[functions.track-shortimize-account]
verify_jwt = true

[functions.check-task-reminders]
verify_jwt = false

[functions.discord-oauth]
verify_jwt = false

[functions.discord-auth]
verify_jwt = false

[functions.x-oauth]
verify_jwt = false

[functions.create-campaign-webhook]
verify_jwt = false

[functions.sync-campaign-video-metrics]
verify_jwt = false

[functions.verify-social-bio]
verify_jwt = true

[functions.create-whop-checkout]
verify_jwt = true

[functions.whop-webhook]
verify_jwt = false
