# fly.toml app configuration file generated for cobalt-virality on 2026-01-07T07:08:53Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cobalt-virality'
primary_region = 'iad'

[build]
  image = 'ghcr.io/imputnet/cobalt:10'

[env]
  API_URL = 'https://cobalt-virality.fly.dev/'
  CORS_WILDCARD = '1'

[http_service]
  internal_port = 9000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
